### ISSUE TITLE
Open Source checklist

### ISSUE THREAD

**Issue by kitallis** [tramlinehq/tramline#306]
- [x] Move all the ee code under a different directory with another license @kitallis 
- [x] Change name of repo from `site` to simply `tramline` @kitallis 
- [x] Figure out licensing and usage for the Mosaic theme @kitallis
- [x] Add a Code of Conduct (see [CC](https://www.contributor-covenant.org/version/2/0/code_of_conduct/), [basecamp](https://basecamp.com/handbook/appendix-07-code-of-conduct), [emblem](https://github.com/GoogleCloudPlatform/emblem/blob/main/CODE_OF_CONDUCT.md))
- [x] Add LICENSE
- [x] Add Security Policy (see [plausible](https://github.com/plausible/analytics/security/policy), [posthog](https://github.com/PostHog/posthog/security/policy))
- [x] Add GitHub topics to repo
- [x] Clean-up the project board
- [x] Issue templates
- [x] Pull request templates
- [x] CI status badge on README
